### PR TITLE
Pattern of Alphabets

### PR DESCRIPTION
**Pull request by nayanapardhekar**
Created a python program to present a pattern of Alphabets using ASCII value.
It contributes to #1

### CODE REVIEW

**Comment by nayanapardhekar** [comment]
Hey, Can you please accept this PR ASAP if it's spot on.

**Review by gautam32 — CHANGES_REQUESTED** [review]
See the examples of the images added by other contributors. You only need to add the pattern image (you can either crop this one or add another image). I also want you to add the changes you made to the README.md file, it's a small edit in the markdown file but it is necessary.

Thank you

**Comment by nayanapardhekar** [comment]
Do I have to make a pull request agian

**Comment by gautam32** [comment]
No, you don't need to make a new PR. Just commit the changes.

**Review by gautam32 — APPROVED** [review]

**Review by gautam32 — APPROVED** [review]

**Comment by nayanapardhekar** [comment]
Can I also add a new pattern in C++ for 4 PR's to complete please!

**Pull request merged**
